### PR TITLE
Abhishek's branch

### PR DESCRIPTION
**Pull request by abhistyalish2802**
added logout button with transfer to login page

### CODE REVIEW

**Review by htdguide — APPROVED** [review]
It's working well, good job!

**Review by Sahil4353 — APPROVED** [review]
Well done Abhishek!

**Review by gaganparmar2003 — APPROVED** [review]
Abhishek i check your code the functions working well of transfering logout page to login.... Well done just make sure when we refresh the page the data that we earlier put will not be saved. The new page must be open as we refresh.

**Comment by abhistyalish2802** [comment]
Thanks

**Pull request merged**
