### PR TITLE
Member Page Working

### PR DESCRIPTION
**Pull request by gaganparmar2003**
I added functionality to edit member page from our website! Check it out.

### CODE REVIEW

**Review by htdguide — APPROVED** [review]

**Comment by Sahil4353** [comment]
Overall, the edit page looks clean and intuitive. Well done!

**Comment by abhistyalish2802** [comment]
I saw your code Gagan that's great work done by you.

**Review by abhistyalish2802 — APPROVED** [review]
well done Gagan I Saw your code

**Review by Sahil4353 — APPROVED** [review]
Good Job Gagan.

**Comment by gnijen** [comment]
Overall, great job on your contribution! Your code demonstrates a solid understanding of both the problem domain and software development. Your code is well-structured and easy to follow. Your code aligns well with our team's coding standards.

**Pull request merged**
